/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list_users_api_auth_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Meta */
    get: operations["meta_api_analytics_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/overview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Overview */
    get: operations["overview_api_analytics_overview_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/inventory-risk": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Inventory */
    get: operations["inventory_api_analytics_inventory_risk_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/query": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Query */
    post: operations["query_api_analytics_query_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/funnel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Funnel */
    post: operations["funnel_api_analytics_funnel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/analytics/cohort": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cohort */
    post: operations["cohort_api_analytics_cohort_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/saved-analyses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Saved */
    get: operations["list_saved_api_saved_analyses_get"];
    put?: never;
    /** Create Saved */
    post: operations["create_saved_api_saved_analyses_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/saved-analyses/{analysis_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Saved */
    get: operations["get_saved_api_saved_analyses__analysis_id__get"];
    put?: never;
    post?: never;
    /** Delete Saved */
    delete: operations["delete_saved_api_saved_analyses__analysis_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/segments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Segments */
    get: operations["list_segments_api_segments_get"];
    put?: never;
    /** Create Segment */
    post: operations["create_segment_api_segments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/segments/{segment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Segment */
    put: operations["update_segment_api_segments__segment_id__put"];
    post?: never;
    /** Delete Segment */
    delete: operations["delete_segment_api_segments__segment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/segments/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Preview Segment */
    post: operations["preview_segment_api_segments_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/anomalies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Anomalies */
    get: operations["list_anomalies_api_anomalies_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/anomalies/{anomaly_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Anomaly */
    get: operations["get_anomaly_api_anomalies__anomaly_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Anomaly */
    patch: operations["update_anomaly_api_anomalies__anomaly_id__patch"];
    trace?: never;
  };
  "/api/anomalies/detect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Detect Now
     * @description Run the detector against the dataset's last day. The worker does this on a
     *     schedule; this endpoint exists so a demo never depends on the scheduler.
     */
    post: operations["detect_now_api_anomalies_detect_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investigations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Investigations */
    get: operations["list_investigations_api_investigations_get"];
    put?: never;
    /** Create Investigation */
    post: operations["create_investigation_api_investigations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investigations/{investigation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Investigation */
    get: operations["get_investigation_api_investigations__investigation_id__get"];
    put?: never;
    post?: never;
    /** Delete Investigation */
    delete: operations["delete_investigation_api_investigations__investigation_id__delete"];
    options?: never;
    head?: never;
    /** Update Investigation */
    patch: operations["update_investigation_api_investigations__investigation_id__patch"];
    trace?: never;
  };
  "/api/investigations/{investigation_id}/findings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Finding */
    post: operations["add_finding_api_investigations__investigation_id__findings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investigations/{investigation_id}/findings/{finding_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Finding */
    delete: operations["delete_finding_api_investigations__investigation_id__findings__finding_id__delete"];
    options?: never;
    head?: never;
    /** Update Finding */
    patch: operations["update_finding_api_investigations__investigation_id__findings__finding_id__patch"];
    trace?: never;
  };
  "/api/investigations/{investigation_id}/actions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Action */
    post: operations["add_action_api_investigations__investigation_id__actions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investigations/{investigation_id}/actions/{action_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Action */
    delete: operations["delete_action_api_investigations__investigation_id__actions__action_id__delete"];
    options?: never;
    head?: never;
    /** Update Action */
    patch: operations["update_action_api_investigations__investigation_id__actions__action_id__patch"];
    trace?: never;
  };
  "/api/stakeholders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Stakeholders */
    get: operations["list_stakeholders_api_stakeholders_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investigations/{investigation_id}/stakeholders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Set Stakeholders */
    put: operations["set_stakeholders_api_investigations__investigation_id__stakeholders_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/root-cause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Root Cause */
    post: operations["root_cause_api_root_cause_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/investigations/{investigation_id}/root-cause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Investigation Root Cause */
    get: operations["investigation_root_cause_api_investigations__investigation_id__root_cause_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Experiments */
    get: operations["list_experiments_api_experiments_get"];
    put?: never;
    /** Create Experiment */
    post: operations["create_experiment_api_experiments_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{experiment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Experiment */
    get: operations["get_experiment_api_experiments__experiment_id__get"];
    put?: never;
    post?: never;
    /** Delete Experiment */
    delete: operations["delete_experiment_api_experiments__experiment_id__delete"];
    options?: never;
    head?: never;
    /** Update Experiment */
    patch: operations["update_experiment_api_experiments__experiment_id__patch"];
    trace?: never;
  };
  "/api/experiments/{experiment_id}/results": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiment Results */
    get: operations["experiment_results_api_experiments__experiment_id__results_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{experiment_id}/memo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiment Memo */
    get: operations["experiment_memo_api_experiments__experiment_id__memo_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiments/{experiment_id}/decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record Decision */
    post: operations["record_decision_api_experiments__experiment_id__decision_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/comments/{entity_type}/{entity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Comments */
    get: operations["list_comments_api_comments__entity_type___entity_id__get"];
    put?: never;
    /** Add Comment */
    post: operations["add_comment_api_comments__entity_type___entity_id__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/comments/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Comment */
    delete: operations["delete_comment_api_comments__comment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActionCreate */
    ActionCreate: {
      /** Title */
      title: string;
      /** Owner Id */
      owner_id?: number | null;
      /** Due Date */
      due_date?: string | null;
    };
    /** ActionOut */
    ActionOut: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      owner: components["schemas"]["UserSummary"] | null;
      status: components["schemas"]["ActionStatus"];
      /** Due Date */
      due_date: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ActionStatus
     * @enum {string}
     */
    ActionStatus: "todo" | "in_progress" | "done";
    /** ActionUpdate */
    ActionUpdate: {
      /** Title */
      title?: string | null;
      /** Owner Id */
      owner_id?: number | null;
      status?: components["schemas"]["ActionStatus"] | null;
      /** Due Date */
      due_date?: string | null;
    };
    /** AnalyticsMeta */
    AnalyticsMeta: {
      /** Data Start */
      data_start: string | null;
      /** Data End */
      data_end: string | null;
      /** Total Events */
      total_events: number;
      /** Metrics */
      metrics: components["schemas"]["MetricInfo"][];
      /** Dimensions */
      dimensions: components["schemas"]["DimensionInfo"][];
      /** Funnel Events */
      funnel_events: {
        [key: string]: string;
      };
    };
    /** AnomalyOut */
    AnomalyOut: {
      /** Id */
      id: number;
      /** Metric Key */
      metric_key: string;
      /** Metric Label */
      metric_label: string;
      /** Metric Format */
      metric_format: string;
      /** Higher Is Better */
      higher_is_better: boolean;
      /** Filters */
      filters: components["schemas"]["Filter"][];
      /** Filter Labels */
      filter_labels: string[];
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /** Ongoing */
      ongoing: boolean;
      /** Expected */
      expected: number;
      /** Actual */
      actual: number;
      /** Zscore */
      zscore: number;
      /** Direction */
      direction: string;
      /** Severity */
      severity: string;
      status: components["schemas"]["AnomalyStatus"];
      /** Investigation Id */
      investigation_id: number | null;
      /**
       * Detected At
       * Format: date-time
       */
      detected_at: string;
    };
    /**
     * AnomalyStatus
     * @enum {string}
     */
    AnomalyStatus: "open" | "acknowledged" | "investigating" | "resolved";
    /** AnomalyUpdate */
    AnomalyUpdate: {
      status: components["schemas"]["AnomalyStatus"];
    };
    /** Candidate */
    Candidate: {
      /** Rank */
      rank: number;
      /**
       * Kind
       * @enum {string}
       */
      kind: "segment" | "release" | "experiment" | "mix_shift";
      /** Title */
      title: string;
      /** Summary */
      summary: string;
      /**
       * Confidence
       * @enum {string}
       */
      confidence: "low" | "medium" | "high";
      /** Dimension */
      dimension?: string | null;
      /** Key */
      key?: string | null;
      /** Explained */
      explained?: number | null;
      /** Filters */
      filters?: components["schemas"]["Filter"][];
      /** Drill */
      drill?: components["schemas"]["Contribution"][];
      /** Drill Dimension */
      drill_dimension?: string | null;
      /** Release Id */
      release_id?: number | null;
      /** Experiment Id */
      experiment_id?: number | null;
      /** Data */
      data?: {
        [key: string]: unknown;
      };
    };
    /** Change */
    Change: {
      /** Baseline */
      baseline: number | null;
      /** Period */
      period: number | null;
      /** Abs Change */
      abs_change: number | null;
      /** Rel Change */
      rel_change: number | null;
      /** Baseline Numerator */
      baseline_numerator: number;
      /** Baseline Denominator */
      baseline_denominator: number | null;
      /** Period Numerator */
      period_numerator: number;
      /** Period Denominator */
      period_denominator: number | null;
    };
    /** Check */
    Check: {
      /** Name */
      name: string;
      /** Passed */
      passed: boolean;
      /** Detail */
      detail: string;
    };
    /** CohortFilter */
    CohortFilter: {
      /** Dimension */
      dimension: string;
      /** Value */
      value: string;
    };
    /** CohortQuery */
    CohortQuery: {
      /**
       * Cohort Type
       * @default signup
       * @enum {string}
       */
      cohort_type: "signup" | "first_purchase";
      /**
       * Measure
       * @default retention
       * @enum {string}
       */
      measure: "retention" | "repeat_purchase" | "revenue_per_user";
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /**
       * Weeks
       * @default 8
       */
      weeks: number;
      /** Filters */
      filters?: components["schemas"]["CohortFilter"][];
    };
    /** CohortResult */
    CohortResult: {
      /**
       * Cohort Type
       * @enum {string}
       */
      cohort_type: "signup" | "first_purchase";
      /**
       * Measure
       * @enum {string}
       */
      measure: "retention" | "repeat_purchase" | "revenue_per_user";
      /** Measure Definition */
      measure_definition: string;
      /** Weeks */
      weeks: number;
      /** Rows */
      rows: components["schemas"]["CohortRow"][];
      /** Interpretation */
      interpretation: {
        [key: string]: unknown;
      };
    };
    /** CohortRow */
    CohortRow: {
      /** Cohort */
      cohort: string;
      /** Size */
      size: number;
      /** Values */
      values: (number | null)[];
    };
    /** CommentCreate */
    CommentCreate: {
      /** Body */
      body: string;
    };
    /** CommentOut */
    CommentOut: {
      /** Id */
      id: number;
      /** Entity Type */
      entity_type: string;
      /** Entity Id */
      entity_id: number;
      author: components["schemas"]["UserSummary"];
      /** Body */
      body: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * Confidence
     * @enum {string}
     */
    Confidence: "low" | "medium" | "high";
    /** Contribution */
    Contribution: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Baseline */
      baseline: number | null;
      /** Period */
      period: number | null;
      /** Rel Change */
      rel_change: number | null;
      /** Share Baseline */
      share_baseline: number;
      /** Share Period */
      share_period: number;
      /** Explained */
      explained: number | null;
      /** Rate Effect */
      rate_effect?: number | null;
      /** Mix Effect */
      mix_effect?: number | null;
      /**
       * Is New
       * @default false
       */
      is_new: boolean;
    };
    /** DecisionIn */
    DecisionIn: {
      decision: components["schemas"]["ExperimentDecision"];
      /** Reason */
      reason: string;
      /**
       * Log
       * @default true
       */
      log: boolean;
    };
    /** DetectionSummary */
    DetectionSummary: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Detected */
      detected: number;
      /** Created */
      created: number;
      /** Updated */
      updated: number;
    };
    /** DimensionBreakdown */
    DimensionBreakdown: {
      /** Dimension */
      dimension: string;
      /** Label */
      label: string;
      /** Contributions */
      contributions: components["schemas"]["Contribution"][];
      /** Concentration */
      concentration: number;
      /**
       * Additive
       * @default true
       */
      additive: boolean;
    };
    /** DimensionInfo */
    DimensionInfo: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      scope: components["schemas"]["Scope"];
      /** Values */
      values: string[];
    };
    /**
     * EntityType
     * @enum {string}
     */
    EntityType: "investigation" | "experiment" | "release" | "analysis" | "decision" | "sop" | "knowledge";
    /** ExperimentCreate */
    ExperimentCreate: {
      /** Name */
      name: string;
      /** Hypothesis */
      hypothesis: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Primary Metric */
      primary_metric: string;
      /** Guardrail Metrics */
      guardrail_metrics?: string[];
      /** Audience Filters */
      audience_filters?: components["schemas"]["Filter"][];
      /**
       * Traffic Percent
       * @default 100
       */
      traffic_percent: number;
      /**
       * Min Sample Per Variant
       * @default 2000
       */
      min_sample_per_variant: number;
      /**
       * Min Relative Effect
       * @default 0.02
       */
      min_relative_effect: number;
      /**
       * Min Duration Days
       * @default 7
       */
      min_duration_days: number;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Key */
      key?: string | null;
      /** Variants */
      variants: components["schemas"]["VariantIn"][];
    };
    /**
     * ExperimentDecision
     * @enum {string}
     */
    ExperimentDecision: "ship" | "iterate" | "stop" | "continue";
    /** ExperimentOut */
    ExperimentOut: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      status: components["schemas"]["ExperimentStatus"];
      owner: components["schemas"]["UserSummary"];
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** End Date */
      end_date: string | null;
      /** Primary Metric */
      primary_metric: string;
      /** Primary Metric Label */
      primary_metric_label: string;
      /** Guardrail Metrics */
      guardrail_metrics: string[];
      /** Traffic Percent */
      traffic_percent: number;
      /** Variant Count */
      variant_count: number;
      decision: components["schemas"]["ExperimentDecision"] | null;
      /** Has Exposure Events */
      has_exposure_events: boolean;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Hypothesis */
      hypothesis: string;
      /** Description */
      description: string;
      /** Audience Filters */
      audience_filters: components["schemas"]["Filter"][];
      /** Filter Labels */
      filter_labels: string[];
      /** Min Sample Per Variant */
      min_sample_per_variant: number;
      /** Min Relative Effect */
      min_relative_effect: number;
      /** Min Duration Days */
      min_duration_days: number;
      /** Variants */
      variants: components["schemas"]["VariantOut"][];
      /** Decision Reason */
      decision_reason: string;
      /** Decided At */
      decided_at: string | null;
      decided_by: components["schemas"]["UserSummary"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ExperimentRef */
    ExperimentRef: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** End Date */
      end_date: string | null;
      /** Primary Metric */
      primary_metric: string;
      /** Guardrail Metrics */
      guardrail_metrics: string[];
      /**
       * Relevance
       * @enum {string}
       */
      relevance: "strong" | "possible" | "weak";
      /** Reason */
      reason: string;
    };
    /** ExperimentResults */
    ExperimentResults: {
      /** Experiment Key */
      experiment_key: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /**
       * Window Start
       * Format: date
       */
      window_start: string;
      /**
       * Window End
       * Format: date
       */
      window_end: string;
      /** Control */
      control: string;
      exposure: components["schemas"]["Exposure"];
      /** Metrics */
      metrics: components["schemas"]["MetricReadout"][];
      /** Timeline */
      timeline: components["schemas"]["TimelinePoint"][];
      /** Segments */
      segments: components["schemas"]["SegmentReadout"][];
      power: components["schemas"]["Power"];
      recommendation: components["schemas"]["Recommendation"];
      /** Notes */
      notes: string[];
    };
    /**
     * ExperimentStatus
     * @enum {string}
     */
    ExperimentStatus: "draft" | "running" | "completed" | "stopped";
    /** ExperimentSummary */
    ExperimentSummary: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      status: components["schemas"]["ExperimentStatus"];
      owner: components["schemas"]["UserSummary"];
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /** End Date */
      end_date: string | null;
      /** Primary Metric */
      primary_metric: string;
      /** Primary Metric Label */
      primary_metric_label: string;
      /** Guardrail Metrics */
      guardrail_metrics: string[];
      /** Traffic Percent */
      traffic_percent: number;
      /** Variant Count */
      variant_count: number;
      decision: components["schemas"]["ExperimentDecision"] | null;
      /** Has Exposure Events */
      has_exposure_events: boolean;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExperimentUpdate */
    ExperimentUpdate: {
      /** Name */
      name?: string | null;
      /** Hypothesis */
      hypothesis?: string | null;
      /** Description */
      description?: string | null;
      status?: components["schemas"]["ExperimentStatus"] | null;
      /** Primary Metric */
      primary_metric?: string | null;
      /** Guardrail Metrics */
      guardrail_metrics?: string[] | null;
      /** Audience Filters */
      audience_filters?: components["schemas"]["Filter"][] | null;
      /** Traffic Percent */
      traffic_percent?: number | null;
      /** Min Sample Per Variant */
      min_sample_per_variant?: number | null;
      /** Min Relative Effect */
      min_relative_effect?: number | null;
      /** Min Duration Days */
      min_duration_days?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Variants */
      variants?: components["schemas"]["VariantIn"][] | null;
    };
    /** Exposure */
    Exposure: {
      /** Total Users */
      total_users: number;
      /** By Variant */
      by_variant: {
        [key: string]: number;
      };
      /** First Exposure */
      first_exposure: string | null;
      /** Last Exposure */
      last_exposure: string | null;
      /** Days Running */
      days_running: number;
      /** Contaminated Users */
      contaminated_users: number;
      srm: components["schemas"]["Srm"] | null;
    };
    /** Filter */
    Filter: {
      /** Dimension */
      dimension: string;
      /**
       * Operator
       * @default eq
       * @enum {string}
       */
      operator: "eq" | "neq" | "in" | "not_in";
      /** Value */
      value?: string | number | null;
      /** Values */
      values?: (string | number)[] | null;
    };
    /** FindingCreate */
    FindingCreate: {
      kind: components["schemas"]["FindingKind"];
      /** Title */
      title: string;
      /**
       * Body
       * @default
       */
      body: string;
      confidence?: components["schemas"]["Confidence"] | null;
      state?: components["schemas"]["HypothesisState"] | null;
      /** Data */
      data?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * FindingKind
     * @enum {string}
     */
    FindingKind: "observation" | "evidence" | "hypothesis" | "recommendation";
    /** FindingOut */
    FindingOut: {
      /** Id */
      id: number;
      kind: components["schemas"]["FindingKind"];
      /** Title */
      title: string;
      /** Body */
      body: string;
      confidence: components["schemas"]["Confidence"] | null;
      state: components["schemas"]["HypothesisState"] | null;
      /** Data */
      data: {
        [key: string]: unknown;
      } | null;
      /** Source */
      source: string;
      author: components["schemas"]["UserSummary"] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** FindingUpdate */
    FindingUpdate: {
      /** Title */
      title?: string | null;
      /** Body */
      body?: string | null;
      confidence?: components["schemas"]["Confidence"] | null;
      state?: components["schemas"]["HypothesisState"] | null;
    };
    /** FunnelQuery */
    FunnelQuery: {
      /** Steps */
      steps?: string[];
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Segments */
      segments?: components["schemas"]["FunnelSegment"][];
      /** Breakdown */
      breakdown?: string | null;
      /**
       * Limit
       * @default 6
       */
      limit: number;
    };
    /** FunnelResult */
    FunnelResult: {
      /** Steps */
      steps: string[];
      /** Window Seconds */
      window_seconds: number;
      /** Series */
      series: components["schemas"]["FunnelSeries"][];
      /** Interpretation */
      interpretation: {
        [key: string]: unknown;
      };
    };
    /** FunnelSegment */
    FunnelSegment: {
      /**
       * Label
       * @default All sessions
       */
      label: string;
      /** Filters */
      filters?: components["schemas"]["Filter"][];
    };
    /** FunnelSeries */
    FunnelSeries: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Filters */
      filters: string[];
      /** Total Sessions */
      total_sessions: number;
      /** Steps */
      steps: components["schemas"]["FunnelStep"][];
    };
    /** FunnelStep */
    FunnelStep: {
      /** Event */
      event: string;
      /** Label */
      label: string;
      /** Sessions */
      sessions: number;
      /** Users */
      users: number;
      /** Step Conversion */
      step_conversion: number | null;
      /** Overall Conversion */
      overall_conversion: number | null;
      /** Drop Off */
      drop_off: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HypothesisState
     * @enum {string}
     */
    HypothesisState: "proposed" | "supported" | "refuted";
    /** InventoryRisk */
    InventoryRisk: {
      /** Product Id */
      product_id: number;
      /** Sku */
      sku: string;
      /** Name */
      name: string;
      /** Category */
      category: string;
      /** Stock Units */
      stock_units: number;
      /** Units Sold 14D */
      units_sold_14d: number;
      /** Daily Velocity */
      daily_velocity: number;
      /** Days Of Cover */
      days_of_cover: number | null;
      /** Revenue 14D */
      revenue_14d: number;
    };
    /** InventoryRiskResult */
    InventoryRiskResult: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /** Threshold Days */
      threshold_days: number;
      /** Items */
      items: components["schemas"]["InventoryRisk"][];
    };
    /** InvestigationCreate */
    InvestigationCreate: {
      /** Title */
      title: string;
      /** Metric Key */
      metric_key: string;
      /** Filters */
      filters?: components["schemas"]["Filter"][];
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /**
       * Baseline Start
       * Format: date
       */
      baseline_start: string;
      /**
       * Baseline End
       * Format: date
       */
      baseline_end: string;
      /**
       * Observation
       * @default
       */
      observation: string;
      /** Anomaly Id */
      anomaly_id?: number | null;
      /** Release Id */
      release_id?: number | null;
      /** Experiment Id */
      experiment_id?: number | null;
    };
    /** InvestigationOut */
    InvestigationOut: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      status: components["schemas"]["InvestigationStatus"];
      owner: components["schemas"]["UserSummary"];
      /** Metric Key */
      metric_key: string;
      /** Metric Label */
      metric_label: string;
      /** Filters */
      filters: components["schemas"]["Filter"][];
      /** Filter Labels */
      filter_labels: string[];
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /** Finding Counts */
      finding_counts: {
        [key: string]: number;
      };
      /** Open Actions */
      open_actions: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Baseline Start
       * Format: date
       */
      baseline_start: string;
      /**
       * Baseline End
       * Format: date
       */
      baseline_end: string;
      /** Observation */
      observation: string;
      /** Decision */
      decision: string;
      /** Resolved At */
      resolved_at: string | null;
      /** Findings */
      findings: components["schemas"]["FindingOut"][];
      /** Actions */
      actions: components["schemas"]["ActionOut"][];
      /** Stakeholders */
      stakeholders: components["schemas"]["InvestigationStakeholderOut"][];
      anomaly: components["schemas"]["AnomalyOut"] | null;
      release: components["schemas"]["LinkedRelease"] | null;
      experiment: components["schemas"]["LinkedExperiment"] | null;
    };
    /** InvestigationStakeholderOut */
    InvestigationStakeholderOut: {
      stakeholder: components["schemas"]["StakeholderOut"];
      /** Role */
      role: string;
    };
    /**
     * InvestigationStatus
     * @enum {string}
     */
    InvestigationStatus: "open" | "investigating" | "validating" | "resolved" | "closed";
    /** InvestigationSummary */
    InvestigationSummary: {
      /** Id */
      id: number;
      /** Title */
      title: string;
      status: components["schemas"]["InvestigationStatus"];
      owner: components["schemas"]["UserSummary"];
      /** Metric Key */
      metric_key: string;
      /** Metric Label */
      metric_label: string;
      /** Filters */
      filters: components["schemas"]["Filter"][];
      /** Filter Labels */
      filter_labels: string[];
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /** Finding Counts */
      finding_counts: {
        [key: string]: number;
      };
      /** Open Actions */
      open_actions: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** InvestigationUpdate */
    InvestigationUpdate: {
      /** Title */
      title?: string | null;
      status?: components["schemas"]["InvestigationStatus"] | null;
      /** Owner Id */
      owner_id?: number | null;
      /** Observation */
      observation?: string | null;
      /** Decision */
      decision?: string | null;
      /** Release Id */
      release_id?: number | null;
      /** Experiment Id */
      experiment_id?: number | null;
      /** Baseline Start */
      baseline_start?: string | null;
      /** Baseline End */
      baseline_end?: string | null;
    };
    /** Kpi */
    Kpi: {
      metric: components["schemas"]["MetricInfo"];
      current: components["schemas"]["Total"];
      previous: components["schemas"]["Total"] | null;
      /** Points */
      points: components["schemas"]["Point"][];
      /** Compare Points */
      compare_points: components["schemas"]["Point"][];
    };
    /** LinkedExperiment */
    LinkedExperiment: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Name */
      name: string;
      /** Status */
      status: string;
      /** Primary Metric */
      primary_metric: string;
    };
    /** LinkedRelease */
    LinkedRelease: {
      /** Id */
      id: number;
      /** Version */
      version: string;
      /** Name */
      name: string;
      /** Platform */
      platform: string;
      /**
       * Release Date
       * Format: date
       */
      release_date: string;
      /** Status */
      status: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** MemoOut */
    MemoOut: {
      /** Markdown */
      markdown: string;
      /**
       * As Of
       * Format: date
       */
      as_of: string;
    };
    /**
     * MetricFormat
     * @enum {string}
     */
    MetricFormat: "count" | "currency" | "percent" | "ratio" | "number" | "days";
    /** MetricInfo */
    MetricInfo: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Description */
      description: string;
      format: components["schemas"]["MetricFormat"];
      /** Higher Is Better */
      higher_is_better: boolean;
      /** Is Proportion */
      is_proportion: boolean;
    };
    /** MetricQuery */
    MetricQuery: {
      /** Metric */
      metric: string;
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Filters */
      filters?: components["schemas"]["Filter"][];
      /** Breakdown */
      breakdown?: string | null;
      /**
       * Granularity
       * @default day
       */
      granularity: ("hour" | "day" | "week") | null;
      /** Compare From */
      compare_from?: string | null;
      /** Compare To */
      compare_to?: string | null;
      /**
       * Limit
       * @default 8
       */
      limit: number;
    };
    /** MetricQueryResult */
    MetricQueryResult: {
      metric: components["schemas"]["MetricInfo"];
      /** Interpretation */
      interpretation: {
        [key: string]: unknown;
      };
      /** Series */
      series: components["schemas"]["Series"][];
    };
    /** MetricReadout */
    MetricReadout: {
      /** Metric Key */
      metric_key: string;
      /** Label */
      label: string;
      /** Format */
      format: string;
      /** Higher Is Better */
      higher_is_better: boolean;
      /**
       * Role
       * @enum {string}
       */
      role: "primary" | "guardrail";
      /** Variants */
      variants: components["schemas"]["VariantStat"][];
      /** Comparisons */
      comparisons: components["schemas"]["VariantComparison"][];
    };
    /** OverviewKpis */
    OverviewKpis: {
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Compare From */
      compare_from: string | null;
      /** Compare To */
      compare_to: string | null;
      /** Kpis */
      kpis: components["schemas"]["Kpi"][];
    };
    /**
     * Permission
     * @enum {string}
     */
    Permission:
      | "view"
      | "run_analytics"
      | "manage_investigations"
      | "manage_experiments"
      | "decide_experiments"
      | "manage_releases"
      | "manage_ops"
      | "manage_decisions"
      | "use_analyst"
      | "manage_users";
    /** Point */
    Point: {
      /** Bucket */
      bucket: string;
      /** Value */
      value: number | null;
      /** Numerator */
      numerator: number;
      /** Denominator */
      denominator: number | null;
    };
    /** Power */
    Power: {
      /** Baseline */
      baseline: number | null;
      /** Required N Per Variant */
      required_n_per_variant: number | null;
      /** Smallest Variant N */
      smallest_variant_n: number;
      /** Detectable Effect Now */
      detectable_effect_now: number | null;
      /** Users Per Day */
      users_per_day: number | null;
      /** Projected Days To Power */
      projected_days_to_power: number | null;
    };
    /** Recommendation */
    Recommendation: {
      /**
       * Decision
       * @enum {string}
       */
      decision: "ship" | "iterate" | "stop" | "continue";
      /**
       * Confidence
       * @enum {string}
       */
      confidence: "low" | "medium" | "high";
      /** Headline */
      headline: string;
      /** Reasons */
      reasons: string[];
      /** Risks */
      risks: string[];
      /** Checks */
      checks: components["schemas"]["Check"][];
    };
    /** ReleaseRef */
    ReleaseRef: {
      /** Id */
      id: number;
      /** Version */
      version: string;
      /** Name */
      name: string;
      /** Platform */
      platform: string;
      /**
       * Release Date
       * Format: date
       */
      release_date: string;
      /** Status */
      status: string;
      /** Days Before Period */
      days_before_period: number;
      /** Affected Areas */
      affected_areas: string[];
      /**
       * Relevance
       * @enum {string}
       */
      relevance: "strong" | "possible" | "weak";
      /** Reason */
      reason: string;
    };
    /**
     * Role
     * @enum {string}
     */
    Role: "admin" | "pm" | "analyst" | "viewer";
    /** RootCauseAnalysis */
    RootCauseAnalysis: {
      /** Metric */
      metric: {
        [key: string]: unknown;
      };
      /** Filters */
      filters: string[];
      /** Period */
      period: {
        [key: string]: string;
      };
      /** Baseline */
      baseline: {
        [key: string]: string;
      };
      overall: components["schemas"]["Change"];
      /** Candidates */
      candidates: components["schemas"]["Candidate"][];
      /** Dimensions */
      dimensions: components["schemas"]["DimensionBreakdown"][];
      /** Supporting */
      supporting: components["schemas"]["SupportingBreakdown"][];
      /** Releases */
      releases: components["schemas"]["ReleaseRef"][];
      /** Experiments */
      experiments: components["schemas"]["ExperimentRef"][];
      /** Notes */
      notes: string[];
    };
    /** RootCauseRequest */
    RootCauseRequest: {
      /** Metric Key */
      metric_key: string;
      /** Filters */
      filters?: components["schemas"]["Filter"][];
      /**
       * Period Start
       * Format: date
       */
      period_start: string;
      /**
       * Period End
       * Format: date
       */
      period_end: string;
      /**
       * Baseline Start
       * Format: date
       */
      baseline_start: string;
      /**
       * Baseline End
       * Format: date
       */
      baseline_end: string;
    };
    /** SavedAnalysisCreate */
    SavedAnalysisCreate: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "analysis" | "funnel" | "cohort";
      /** Config */
      config: {
        [key: string]: unknown;
      };
    };
    /** SavedAnalysisOut */
    SavedAnalysisOut: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: "analysis" | "funnel" | "cohort";
      /** Config */
      config: {
        [key: string]: unknown;
      };
      /** Id */
      id: number;
      owner: components["schemas"]["UserSummary"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * Scope
     * @enum {string}
     */
    Scope: "session" | "event";
    /** SegmentCreate */
    SegmentCreate: {
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /** Conditions */
      conditions: components["schemas"]["Filter"][];
    };
    /** SegmentMetric */
    SegmentMetric: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Format */
      format: string;
      /** Value */
      value: number | null;
      /** Compare Value */
      compare_value?: number | null;
      /** Baseline Value */
      baseline_value?: number | null;
    };
    /** SegmentOut */
    SegmentOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Conditions */
      conditions: components["schemas"]["Filter"][];
      owner: components["schemas"]["UserSummary"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** SegmentPreview */
    SegmentPreview: {
      /** Conditions */
      conditions: string[];
      /** Metrics */
      metrics: components["schemas"]["SegmentMetric"][];
    };
    /** SegmentPreviewRequest */
    SegmentPreviewRequest: {
      /** Conditions */
      conditions?: components["schemas"]["Filter"][];
      /**
       * Date From
       * Format: date
       */
      date_from: string;
      /**
       * Date To
       * Format: date
       */
      date_to: string;
      /** Compare From */
      compare_from?: string | null;
      /** Compare To */
      compare_to?: string | null;
    };
    /** SegmentReadout */
    SegmentReadout: {
      /** Dimension */
      dimension: string;
      /** Label */
      label: string;
      /** Rows */
      rows: components["schemas"]["SegmentRow"][];
    };
    /** SegmentRow */
    SegmentRow: {
      /** Segment */
      segment: string;
      /** Users */
      users: number;
      /** Control */
      control: number | null;
      /** Treatment */
      treatment: number | null;
      /** Rel Diff */
      rel_diff: number | null;
      /** P Value */
      p_value: number | null;
      /** Significant */
      significant: boolean;
    };
    /** Series */
    Series: {
      /** Key */
      key: string;
      /** Label */
      label: string;
      total: components["schemas"]["Total"];
      compare_total?: components["schemas"]["Total"] | null;
      /** Points */
      points?: components["schemas"]["Point"][];
      /** Compare Points */
      compare_points?: components["schemas"]["Point"][];
    };
    /** Srm */
    Srm: {
      /** Chi2 */
      chi2: number;
      /** P Value */
      p_value: number;
      /** Mismatch */
      mismatch: boolean;
      /** Expected */
      expected: {
        [key: string]: number;
      };
    };
    /** StakeholderAssignment */
    StakeholderAssignment: {
      /** Stakeholder Id */
      stakeholder_id: number;
      /**
       * Role
       * @default informed
       */
      role: string;
    };
    /** StakeholderOut */
    StakeholderOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Email */
      email: string;
      /** Team */
      team: string;
      /** Title */
      title: string;
    };
    /** SupportingBreakdown */
    SupportingBreakdown: {
      /** Title */
      title: string;
      /** Dimension */
      dimension: string;
      /** Rows */
      rows: {
        [key: string]: unknown;
      }[];
    };
    /** TimelinePoint */
    TimelinePoint: {
      /**
       * Day
       * Format: date
       */
      day: string;
      /** Cumulative */
      cumulative: {
        [key: string]: number | null;
      };
      /** Users */
      users: {
        [key: string]: number;
      };
    };
    /** Total */
    Total: {
      /** Value */
      value: number | null;
      /** Numerator */
      numerator: number;
      /** Denominator */
      denominator: number | null;
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: number;
      /** Email */
      email: string;
      /** Name */
      name: string;
      role: components["schemas"]["Role"];
      /** Permissions */
      permissions: components["schemas"]["Permission"][];
    };
    /** UserSummary */
    UserSummary: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Email */
      email: string;
      role: components["schemas"]["Role"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VariantComparison */
    VariantComparison: {
      /** Variant */
      variant: string;
      /** Abs Diff */
      abs_diff: number;
      /** Rel Diff */
      rel_diff: number | null;
      /** Ci Low */
      ci_low: number;
      /** Ci High */
      ci_high: number;
      /** Rel Ci Low */
      rel_ci_low: number | null;
      /** Rel Ci High */
      rel_ci_high: number | null;
      /** P Value */
      p_value: number;
      /** Significant */
      significant: boolean;
      /**
       * Direction
       * @enum {string}
       */
      direction: "better" | "worse" | "flat";
    };
    /** VariantIn */
    VariantIn: {
      /** Key */
      key: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Weight
       * @default 50
       */
      weight: number;
      /**
       * Is Control
       * @default false
       */
      is_control: boolean;
    };
    /** VariantOut */
    VariantOut: {
      /** Key */
      key: string;
      /** Name */
      name: string;
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Weight
       * @default 50
       */
      weight: number;
      /**
       * Is Control
       * @default false
       */
      is_control: boolean;
      /** Id */
      id: number;
    };
    /** VariantStat */
    VariantStat: {
      /** Key */
      key: string;
      /** Users */
      users: number;
      /** Value */
      value: number | null;
      /** Numerator */
      numerator: number;
      /** Denominator */
      denominator: number;
      /** Ci Low */
      ci_low: number | null;
      /** Ci High */
      ci_high: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  me_api_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserOut"];
        };
      };
    };
  };
  list_users_api_auth_users_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSummary"][];
        };
      };
    };
  };
  meta_api_analytics_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalyticsMeta"];
        };
      };
    };
  };
  overview_api_analytics_overview_get: {
    parameters: {
      query: {
        date_from: string;
        date_to: string;
        compare_from?: string | null;
        compare_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OverviewKpis"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  inventory_api_analytics_inventory_risk_get: {
    parameters: {
      query: {
        as_of: string;
        threshold_days?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InventoryRiskResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  query_api_analytics_query_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MetricQuery"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetricQueryResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  funnel_api_analytics_funnel_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FunnelQuery"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FunnelResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cohort_api_analytics_cohort_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CohortQuery"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CohortResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_saved_api_saved_analyses_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedAnalysisOut"][];
        };
      };
    };
  };
  create_saved_api_saved_analyses_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SavedAnalysisCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedAnalysisOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_saved_api_saved_analyses__analysis_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SavedAnalysisOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_saved_api_saved_analyses__analysis_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        analysis_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_segments_api_segments_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SegmentOut"][];
        };
      };
    };
  };
  create_segment_api_segments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SegmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SegmentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_segment_api_segments__segment_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        segment_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SegmentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SegmentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_segment_api_segments__segment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        segment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_segment_api_segments_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SegmentPreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SegmentPreview"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_anomalies_api_anomalies_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["AnomalyStatus"] | null;
        metric?: string | null;
        severity?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnomalyOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_anomaly_api_anomalies__anomaly_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        anomaly_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnomalyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_anomaly_api_anomalies__anomaly_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        anomaly_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnomalyUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnomalyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  detect_now_api_anomalies_detect_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DetectionSummary"];
        };
      };
    };
  };
  list_investigations_api_investigations_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["InvestigationStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvestigationSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_investigation_api_investigations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvestigationCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvestigationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_investigation_api_investigations__investigation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvestigationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_investigation_api_investigations__investigation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_investigation_api_investigations__investigation_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvestigationUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvestigationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_finding_api_investigations__investigation_id__findings_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FindingCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindingOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_finding_api_investigations__investigation_id__findings__finding_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
        finding_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_finding_api_investigations__investigation_id__findings__finding_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
        finding_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FindingUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FindingOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_action_api_investigations__investigation_id__actions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_action_api_investigations__investigation_id__actions__action_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
        action_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_action_api_investigations__investigation_id__actions__action_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
        action_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_stakeholders_api_stakeholders_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StakeholderOut"][];
        };
      };
    };
  };
  set_stakeholders_api_investigations__investigation_id__stakeholders_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StakeholderAssignment"][];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvestigationOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  root_cause_api_root_cause_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RootCauseRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RootCauseAnalysis"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  investigation_root_cause_api_investigations__investigation_id__root_cause_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investigation_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RootCauseAnalysis"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_experiments_api_experiments_get: {
    parameters: {
      query?: {
        status?: components["schemas"]["ExperimentStatus"] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_experiment_api_experiments_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExperimentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_experiment_api_experiments__experiment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_experiment_api_experiments__experiment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_experiment_api_experiments__experiment_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExperimentUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  experiment_results_api_experiments__experiment_id__results_get: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: never;
      path: {
        experiment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentResults"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  experiment_memo_api_experiments__experiment_id__memo_get: {
    parameters: {
      query?: {
        as_of?: string | null;
      };
      header?: never;
      path: {
        experiment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemoOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  record_decision_api_experiments__experiment_id__decision_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experiment_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DecisionIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExperimentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_comments_api_comments__entity_type___entity_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entity_type: components["schemas"]["EntityType"];
        entity_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_comment_api_comments__entity_type___entity_id__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entity_type: components["schemas"]["EntityType"];
        entity_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentOut"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_comment_api_comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
