"""feedback

Revision ID: f69df8391063
Revises: 89dc64039f93
Create Date: 2026-09-13 22:53:07.785185
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "f69df8391063"
down_revision: str | None = "89dc64039f93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("stakeholder_id", sa.Integer(), nullable=True),
        sa.Column("submitted_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "support",
                "interview",
                "survey",
                "sales",
                "app_review",
                "internal",
                name="feedbacksource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("theme", sa.String(length=60), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "sentiment",
            sa.Enum(
                "negative", "neutral", "positive", name="feedbacksentiment", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "triaged",
                "planned",
                "addressed",
                "dismissed",
                name="feedbackstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("platform", sa.String(length=20), nullable=True),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("linked_entity_type", sa.String(length=32), nullable=True),
        sa.Column("linked_entity_id", sa.Integer(), nullable=True),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(theme, '') || ' ' || coalesce(body, ''))", persisted=True
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stakeholder_id"],
            ["stakeholders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_feedback_search", "feedback", ["search_vector"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_feedback_theme"), "feedback", ["theme"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_theme"), table_name="feedback")
    op.drop_index("ix_feedback_search", table_name="feedback", postgresql_using="gin")
    op.drop_table("feedback")
    # ### end Alembic commands ###
